apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: integration-cip-skidspar
  name: integration-cip-skidspar
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: integration-cip-skidspar
  name: integration-cip-skidspar
spec:
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: integration-cip-skidspar
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            app.kubernetes.io/name: integration-cip-skidspar
        spec:
          containers:
          - env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            image: ghcr.io/diwise/integration-cip-skidspar@sha256:notbuiltyet
            imagePullPolicy: IfNotPresent
            name: integration-cip-skidspar
            resources:
              limits:
                cpu: 100m
                memory: 250Mi
              requests:
                cpu: 50m
                memory: 100Mi
          restartPolicy: Never
          serviceAccountName: integration-cip-skidspar
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 1
